### ISSUE TITLE
Web Suport

### ISSUE THREAD

**Issue by PaulRedFoxCode** [jonataslaw/readmore#7] opened 2020-11-19 21:14 UTC
I use your package for an website app. If I build for Android and windows is working, for the web it`s a simple text.
Can you check your package for web-support?
Thank you for your work!

**Comment by karabanovbs** [comment] 2021-02-18 00:11
[flutter issue](https://github.com/flutter/flutter/issues/65940)

**Comment by maRci002** [comment] 2023-01-26 15:32
It seems flutter/engine#34085 PR did fix the issue it is available in Flutter 3.7.0 stable release.

**Comment by jonataslaw** [comment] 2024-03-28 00:15
Closing it, since the problem is not present in current version.

**Closed by jonataslaw** 2024-03-28 00:15 UTC
